# Project information
site_name: SeleniumBase Docs
site_url: https://seleniumbase.io
site_author: Michael Mintz
site_description: A complete framework for end-to-end testing with Python, pytest, and WebDriver.
# Repository information
repo_name: seleniumbase/SeleniumBase
repo_url: https://github.com/seleniumbase/SeleniumBase
edit_uri: ""
site_dir: "site"
docs_dir: "docs"
# Copyright
copyright: Copyright &copy; 2014 - 2021 Michael Mintz
# Extensions
markdown_extensions:
  - admonition
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight:
      linenums: false
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.snippets
# Configuration
theme:
  name: material
  logo: img/grad_logo.png
  favicon: img/grad_logo.png
  language: en
  include_homepage_in_sidebar: true
  sticky_navigation: true
  collapse_navigation: true
  # titles_only: false
  include_search_page: false
  search_index_only: true
  static_templates:
    - 404.html
  features:
    # - search.highlight
    - toc.integrate
    - navigation.indexes
    # - navigation.sections
    - navigation.expand
    # - navigation.tabs
    - navigation.tracking
    - navigation.instant
  palette:
    scheme: default
    primary: blue
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: img/sb_logo_10.png
# Plugins
plugins:
  - search:
      separator: '[\s]+'
      lang: en
  - exclude-search:
      exclude:
        - help_docs/chinese.md
        - integrations/katalon/ReadMe.md
        - seleniumbase/utilities/selenium_ide/ReadMe.md
  - minify:
      minify_html: true
  - mkdocs-simple-hooks:
      hooks:
        on_pre_build: docs.prepare:main
# Page tree
nav:
  - SeleniumBase ReadMe: README.md
  - Features List: help_docs/features_list.md
  - Running Example Tests: examples/ReadMe.md
  - Command Line Options: help_docs/customizing_test_runs.md
  - Dashboard / Reports: examples/example_logs/ReadMe.md
  - Console Scripts: seleniumbase/console_scripts/ReadMe.md
  - Syntax Formats: help_docs/syntax_formats.md
  - Recorder Mode: help_docs/recorder_mode.md
  - API Reference: help_docs/method_summary.md
  - Setup / Install:
    - Install Python, pip, git: help_docs/install_python_pip_git.md
    - Virtualenv Instructions: help_docs/virtualenv_instructions.md
    - Install SeleniumBase: help_docs/install.md
    - WebDriver Installation: help_docs/webdriver_installation.md
    - Verifying WebDriver: help_docs/verify_webdriver.md
    - How it Works: help_docs/how_it_works.md
  - Languages:
    - Translations: help_docs/translations.md
    - Chinese Docs: help_docs/chinese.md
    - Locale Codes: help_docs/locale_codes.md
  - JS Generators:
    - Tour Maker: examples/tour_examples/ReadMe.md
    - Dialog Boxes: examples/dialog_boxes/ReadMe.md
    - Chart Maker: help_docs/chart_maker.md
    - Presentation Maker: examples/presenter/ReadMe.md
  - Integrations:
    - Mobile Testing: help_docs/mobile_testing.md
    - GitHub CI: integrations/github/workflows/ReadMe.md
    - Visual Testing: examples/visual_testing/ReadMe.md
    - Selenium Grid: seleniumbase/utilities/selenium_grid/ReadMe.md
    - HighCharts: examples/chart_maker/ReadMe.md
    - MasterQA: examples/master_qa/ReadMe.md
    - Jenkins on Azure: integrations/azure/jenkins/ReadMe.md
    - Jenkins on Google Cloud: integrations/google_cloud/ReadMe.md
    - NodeJS Test Runner: https://github.com/seleniumbase/SeleniumBase/tree/master/integrations/node_js
    - Katalon Recorder Export: integrations/katalon/ReadMe.md
    - Selenium IDE Export: seleniumbase/utilities/selenium_ide/ReadMe.md
  - Help Docs:
    - Table of Contents: help_docs/ReadMe.md
    - JS Package Manager: help_docs/js_package_manager.md
    - Master QA Hybrid Mode: seleniumbase/masterqa/ReadMe.md
    - Decorators / Security: seleniumbase/common/ReadMe.md
    - Desired Capabilities: help_docs/desired_capabilities.md
    - Docker Start Guide: integrations/docker/ReadMe.md
    - Using Safari Driver: help_docs/using_safari_driver.md
    - Shadow DOM Support: help_docs/shadow_dom.md
    - The HTML Inspector: help_docs/html_inspector.md
    - macOS Hidden Files: help_docs/hidden_files_info.md
    - MySQL Instructions: help_docs/mysql_installation.md
  - Demo Pages:
    - Demo Page / Demo Site: https://seleniumbase.io/demo_page
    - TinyMCE Demo Page: https://seleniumbase.io/tinymce/
    - Drag & Drop Demo Page: https://seleniumbase.io/other/drag_and_drop
    - Virtual Device Farm: https://seleniumbase.io/devices/
    - Error Demo Page: https://seleniumbase.io/error_page/
    - Page with broken links: https://seleniumbase.io/other/broken_page
    - W3Schools iframes: https://seleniumbase.io/w3schools/iframes
    - W3Schools doubleclick: https://seleniumbase.io/w3schools/double_click
    - W3Schools checkboxes: https://seleniumbase.io/w3schools/checkboxes
    - W3Schools drag & drop: https://seleniumbase.io/w3schools/drag_drop
    - W3Schools radio buttons: https://seleniumbase.io/w3schools/radio_buttons
    - SeleniumBase in iframe: https://seleniumbase.io/w3schools/sbase
    - HTML Playground Page: https://seleniumbase.io/w3schools/
  - Presentations:
    - Presenter Demo: https://seleniumbase.io/other/presenter.html
    - Core Presentation: https://seleniumbase.io/other/core_presentation.html
    - Chart Maker Demo: https://seleniumbase.io/other/chart_presentation.html
    - Virtual Env Tutorial: https://seleniumbase.io/other/py_virtual_envs.html
  - Other:
    - YouTube Link: https://www.youtube.com/playlist?list=PLp9uKicxkBc5UIlGi2BuE3aWC7JyXpD3m
    - Case Studies: help_docs/happy_customers.md
    - Thank You: help_docs/thank_you.md
# Google Analytics
extra:
  analytics:
    provider: google
    property: UA-167313767-1
# google_analytics: ['UA-167313767-1', 'seleniumbase.io']