# Project information
site_name: SeleniumBase Docs
site_url: https://seleniumbase.io
site_author: Michael Mintz
site_description: A complete framework for end-to-end testing with Python, pytest, behave-BDD, and WebDriver.
# Repository information
repo_name: seleniumbase/SeleniumBase
repo_url: https://github.com/seleniumbase/SeleniumBase
edit_uri: ""
site_dir: "site"
docs_dir: "mkdocs_build"
# Copyright
copyright: Copyright &copy; 2014 - 2024 Michael Mintz
# Extensions
markdown_extensions:
  - admonition
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight:
      linenums: false
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  # - pymdownx.details
  # - pymdownx.snippets
# Configuration
theme:
  name: material
  logo: img/logo3c.png
  favicon: img/green_logo3.png
  language: en
  include_homepage_in_sidebar: true
  sticky_navigation: true
  collapse_navigation: true
  # titles_only: false
  include_search_page: false
  search_index_only: true
  static_templates:
    - 404.html
  features:
    # - search.highlight
    # - toc.integrate
    - toc.hide
    # - navigation.indexes
    - toc.follow
    - navigation.sections
    # - navigation.expand
    # - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.instant
  palette:
    scheme: default
    primary: blue
    accent: green
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: img/sb_logo_10.png
# Plugins
plugins:
  - search:
      separator: '[\s]+'
      lang: en
  - exclude-search:
      exclude:
        - CODE_OF_CONDUCT.md
        - CONTRIBUTING.md
        - SECURITY.md
        - examples/case_summary.md
        - help_docs/chinese.md
        - integrations/katalon/ReadMe.md
        - help_docs/ReadMe.md
        - help_docs/verify_webdriver.md
        - help_docs/webdriver_installation.md
        - seleniumbase/masterqa/ReadMe.md
        - seleniumbase/utilities/selenium_ide/ReadMe.md
        - seleniumbase/examples/chart_maker/ReadMe.md
  # - minify:
  #     minify_html: true
  #     minify_css: true
  #     minify_js: true
  - mkdocs-simple-hooks:
      hooks:
        on_pre_build: mkdocs_build.prepare:main
# Page tree
nav:
  - âœ… SeleniumBase README: README.md
  - ğŸ° List of Features: help_docs/features_list.md
  - ğŸ“š Running Example Tests: examples/ReadMe.md
  - ğŸ›ï¸ Command Line Options: help_docs/customizing_test_runs.md
  - ğŸŒ  Console Scripts: seleniumbase/console_scripts/ReadMe.md
  - ğŸ“Š Dashboard / Reports: examples/example_logs/ReadMe.md
  - ğŸ”¡ Syntax Formats: help_docs/syntax_formats.md
  - ğŸ–ï¸ GUI / Commander: help_docs/commander.md
  - ğŸ”´ Recorder Mode: help_docs/recorder_mode.md
  - ğŸ“˜ API Reference: help_docs/method_summary.md
  - Python Setup / Install:
    - ğŸ‰ Get Python, pip, & git: help_docs/install_python_pip_git.md
    - âš™ï¸ Virtualenv Instructions: help_docs/virtualenv_instructions.md
    - ğŸ„ Install SeleniumBase: help_docs/install.md
    - ğŸ‘ï¸ How it Works: help_docs/how_it_works.md
  - JS Manager / JS Tools:
    - ğŸ•¹ï¸ Package Manager: help_docs/js_package_manager.md
    - ğŸ¦ Demo Mode: help_docs/demo_mode.md
    - ğŸš Tour Maker: examples/tour_examples/ReadMe.md
    - ğŸ›‚ Dialog Boxes: examples/dialog_boxes/ReadMe.md
    - ğŸ›‚ MasterQA Mode: examples/master_qa/ReadMe.md
    - ğŸ“¶ Chart Maker: examples/chart_maker/ReadMe.md
    - ğŸï¸ Presentation Maker: examples/presenter/ReadMe.md
  - Integrations:
    - ğŸ‘¤ UC Mode: help_docs/uc_mode.md
    - ğŸ™ CDP Mode: examples/cdp_mode/ReadMe.md
    - ğŸ¤– GitHub CI: integrations/github/workflows/ReadMe.md
    - ğŸ›‚ MasterQA: seleniumbase/masterqa/ReadMe.md
    - ğŸ—‚ï¸ Case Plans: help_docs/case_plans.md
    - ğŸ“± Mobile Mode: help_docs/mobile_testing.md
    - ğŸŒ Selenium Grid: seleniumbase/utilities/selenium_grid/ReadMe.md
    - ğŸ–¼ï¸ Visual Testing: examples/visual_testing/ReadMe.md
    - ğŸ•µï¸ The HTML Inspector: help_docs/html_inspector.md
    - ğŸ¤– Azure Pipelines: integrations/azure/azure_pipelines/ReadMe.md
    - ğŸ¤– Jenkins on Azure: integrations/azure/jenkins/ReadMe.md
    - ğŸ¤– Jenkins on Google Cloud: integrations/google_cloud/ReadMe.md
    - ğŸ¤– NodeJS Test Runner: https://github.com/seleniumbase/SeleniumBase/tree/master/integrations/node_js
  - Presentations:
    - âœ… Core Presentation: https://seleniumbase.io/other/core_presentation.html
    - ğŸï¸ Presenter Demo: https://seleniumbase.io/other/presenter.html
    - ğŸ“Š Chart Maker Demo: https://seleniumbase.io/other/chart_presentation.html
    - âš™ï¸ Python Virtual Envs: https://seleniumbase.io/other/py_virtual_envs.html
    - ğŸ”° Fundamentals Demo: https://seleniumbase.io/other/fundamentals.html
  - Demo Pages:
    - ğŸµ Coffee Cart (Test App): https://seleniumbase.io/coffee/
    - ğŸ“‘ Demo Page (Test Page): https://seleniumbase.io/demo_page
    - ğŸ”‘ Simple App (Test Page): https://seleniumbase.io/simple/login
    - ğŸ”‘ MFA Login (Test App): https://seleniumbase.io/realworld/login
    - ğŸ“ TinyMCE (Test Page): https://seleniumbase.io/tinymce/
    - ğŸ”¢ Calculator (Test App): https://seleniumbase.io/apps/calculator
    - ğŸ“± Device Farm (Virtual): https://seleniumbase.io/devices/
    - âš ï¸ Error Page (Test Page): https://seleniumbase.io/error_page/
    - âš ï¸ Page with broken links: https://seleniumbase.io/other/broken_page
    - â†”ï¸ Drag & Drop (Test Page): https://seleniumbase.io/other/drag_and_drop
    - ğŸ–¼ï¸ Canvas Test Page One: https://seleniumbase.io/canvas/
    - ğŸ–¼ï¸ Canvas Test Page Two: https://seleniumbase.io/other/canvas
    - ğŸ‘¤ Shadow DOM/Root Page: https://seleniumbase.io/other/shadow_dom
    - ğŸ–¥ï¸ SeleniumBase in iframe: https://seleniumbase.io/w3schools/sbase
    - ğŸ–¥ï¸ W3Schools Playground: https://seleniumbase.io/w3schools/
    - ğŸ–¥ï¸ W3Schools iframes: https://seleniumbase.io/w3schools/iframes
    - ğŸ—ƒï¸ W3Schools file upload: https://seleniumbase.io/w3schools/file_upload
    - ğŸ–²ï¸ W3Schools doubleclick: https://seleniumbase.io/w3schools/double_click
    - â†”ï¸ W3Schools drag & drop: https://seleniumbase.io/w3schools/drag_drop
    - â˜‘ï¸ W3Schools checkboxes: https://seleniumbase.io/w3schools/checkboxes
    - ğŸ”˜ W3Schools radio buttons: https://seleniumbase.io/w3schools/radio_buttons
  - Pages with CAPTCHAs:
    - ğŸ”‘ CF Turnstile Test: https://seleniumbase.io/apps/turnstile
    - ğŸ”‘ CF Turnstile on Form: https://seleniumbase.io/apps/form_turnstile
    - ğŸ” reCAPTCHA v2 Test: https://seleniumbase.io/apps/recaptcha
    - ğŸ” reCAPTCHA v2 on Form: https://seleniumbase.io/apps/form_recaptcha
    - ğŸ” reCAPTCHA, invisible: https://seleniumbase.io/apps/invisible_recaptcha
  - Additional Help Docs:
    - ğŸ“‘ Table of Contents: help_docs/ReadMe.md
    - ğŸ–¼ï¸ How to handle iframes: help_docs/handling_iframes.md
    - ğŸ” Decorators / Security: seleniumbase/common/ReadMe.md
    - ğŸ—‚ï¸ Case Plans (examples): examples/case_summary.md
    - ğŸ§­ Using Safari Driver: help_docs/using_safari_driver.md
    - ğŸ³ Docker Start Guide: integrations/docker/ReadMe.md
    - ğŸ‘¤ Shadow DOM Support: help_docs/shadow_dom.md
    - ğŸ‘¥ macOS Hidden Files: help_docs/hidden_files_info.md
    - ğŸ—„ï¸ MySQL Instructions: help_docs/mysql_installation.md
    - ğŸ“ƒ Desired Capabilities: help_docs/desired_capabilities.md
    - ğŸ“œ Useful grep commands: help_docs/useful_grep_commands.md
    - âš™ï¸ Downloading drivers: help_docs/webdriver_installation.md
    - âœ”ï¸ Verifying drivers: help_docs/verify_webdriver.md
  - Behave-BDD Integration:
    - ğŸ Behave-BDD ReadMe: examples/behave_bdd/ReadMe.md
    - ğŸ Behave-BDD GUI App: help_docs/behave_gui.md
  - Languages:
    - ğŸŒ Translations: help_docs/translations.md
    - ğŸ² Chinese Docs: help_docs/chinese.md
    - ğŸ—¾ Locale Codes: help_docs/locale_codes.md
  - Other:
    - ğŸ“º YouTube Link: https://www.youtube.com/playlist?list=PLp9uKicxkBc5UIlGi2BuE3aWC7JyXpD3m
    - ğŸ“‹ Case Studies: help_docs/happy_customers.md
    - ğŸ™ Thank You: help_docs/thank_you.md
# Google Analytics
extra:
  analytics:
    provider: google
    property: G-P5KFWRNLRN
    # property: UA-167313767-1
# google_analytics: ['G-P5KFWRNLRN', 'seleniumbase.io']