# Project information
site_name: SeleniumBase
site_url: https://seleniumbase.io
site_author: Michael Mintz
site_description: A fast & reliable web automation framework for end-to-end testing with Python, pytest and WebDriver. Includes tools for reporting, visual testing, RPA, and more.
# Repository information
repo_name: seleniumbase/SeleniumBase
repo_url: https://github.com/seleniumbase/SeleniumBase
edit_uri: ""
site_dir: "site"
docs_dir: "docs"
# Copyright
copyright: Copyright &copy; 2014 - 2021 Michael Mintz / SeleniumBase
# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite
  - markdown.extensions.meta
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.toc:
      permalink: true
# Configuration
theme:
  name: material
  logo: img/grad_logo.png
  favicon: img/grad_logo.png
  include_homepage_in_sidebar: true
  sticky_navigation: true
  language: en
  include_search_page: false
  search_index_only: false
  features:
    - tabs
    - instant
  palette:
    scheme: default
    primary: blue
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: img/sb_logo_7.png
# Plugins
plugins:
  - search
  - minify:
      minify_html: false
  - mkdocs-simple-hooks:
      hooks:
        on_pre_build: docs.prepare:main
# Page tree
nav:
  - SeleniumBase / ReadMe: README.md
  - Features List: help_docs/features_list.md
  - Running Example Tests: examples/ReadMe.md
  - Command Line Options: help_docs/customizing_test_runs.md
  - Dashboard / Reports: examples/example_logs/ReadMe.md
  - Console Scripts: seleniumbase/console_scripts/ReadMe.md
  - Syntax Formats: help_docs/syntax_formats.md
  - API Reference: help_docs/method_summary.md
  - Setup / Install:
    - Install Python, pip, git: help_docs/install_python_pip_git.md
    - Virtualenv Instructions: help_docs/virtualenv_instructions.md
    - Install SeleniumBase: help_docs/install.md
    - WebDriver Installation: help_docs/webdriver_installation.md
    - Verifying WebDriver: help_docs/verify_webdriver.md
    - How it Works: help_docs/how_it_works.md
  - Languages:
    - Translations: help_docs/translations.md
    - Chinese / 中文文件: help_docs/chinese.md
    - Locale Codes: help_docs/locale_codes.md
  - JS Generators:
    - Tour Maker: examples/tour_examples/ReadMe.md
    - Presentation Maker: examples/presenter/ReadMe.md
    - Chart Maker: help_docs/chart_maker.md
  - Integrations:
    - Mobile Testing: help_docs/mobile_testing.md
    - GitHub CI: integrations/github/workflows/ReadMe.md
    - Selenium Grid: seleniumbase/utilities/selenium_grid/ReadMe.md
    - Katalon Recorder: integrations/katalon/ReadMe.md
    - MasterQA: examples/master_qa/ReadMe.md
    - Visual Testing: examples/visual_testing/ReadMe.md
    - Jenkins on Azure: integrations/azure/jenkins/ReadMe.md
    - Jenkins on Google Cloud: integrations/google_cloud/ReadMe.md
    - Recorder Export/Convert: seleniumbase/utilities/selenium_ide/ReadMe.md
    - NodeJS Test Runner: https://github.com/seleniumbase/SeleniumBase/tree/master/integrations/node_js
    - HighCharts: examples/chart_maker/ReadMe.md
  - Help Docs:
    - Table of Contents: help_docs/ReadMe.md
    - Master QA: seleniumbase/masterqa/ReadMe.md
    - JS Package Manager: help_docs/js_package_manager.md
    - Decorators & Security: seleniumbase/common/ReadMe.md
    - Desired Capabilities: help_docs/desired_capabilities.md
    - Using Safari Driver: help_docs/using_safari_driver.md
    - macOS Hidden Files: help_docs/hidden_files_info.md
    - Docker Help: integrations/docker/ReadMe.md
    - MySQL Help: help_docs/mysql_installation.md
    - Case Studies: help_docs/happy_customers.md
  - Demo Pages:
    - Demo Page / Demo Site: https://seleniumbase.io/demo_page
    - TinyMCE Demo Page: https://seleniumbase.io/other/tinymce
    - Virtual Device Farm: https://seleniumbase.io/devices/
    - Error Demo Page: https://seleniumbase.io/error_page/
  - Presentations:
    - Presenter Demo: https://seleniumbase.io/other/presenter.html
    - Core Presentation: https://seleniumbase.io/other/core_presentation.html
    - Chart Maker Demo: https://seleniumbase.io/other/chart_presentation.html
    - Virtual Env Tutorial: https://seleniumbase.io/other/py_virtual_envs.html
  - Thank You: help_docs/thank_you.md
# Google Analytics
google_analytics: ['UA-167313767-1', 'seleniumbase.io']